on:
  pull_request:
    branches: [ master ]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: A job to create dynamic checklist
    steps:
      - name: Dynamic checklist action
        id: dynamic_checklist
        uses: vishalsinha21/dc-github-action@v2
        with:
          mappingFile: './mapping.json'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get the output checklist
        run: echo "The final checklist ${{ steps.dynamic_checklist.outputs.checklist }}"

