on:
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: vishalsinha21/github-actions-hello-world@v2
        with:
          who-to-greet: 'Vishal!'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Dynamic checklist action
        id: dynamic_checklist
      - uses: vishalsinha21/dc-github-action@v1
        with:
          mappingFile: 'mapping.json'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get the output checklist
        run: echo "The final checklist ${{ steps.dynamic_checklist.outputs.checklist }}"
