on:
  pull_request:
    branches: [ master ]

env:
  input1: value1
  input2: value2
  input3:
    input31: value31
    input32: value32
  mappings:
    - keywords:
      - create index
      - createIndex
      comment: Indexes have been created concurrently in big tables
    - keywords:
      - connection
      - session
      - CloseableHttpClient
      - HttpClient
      comment: Resources have been closed in finally block or using try-with-resources
    - keywords:
      - RequestMapping
      - GetMapping
      - PostMapping
      - PutMapping
      comment: Endpoint URLs exposed by application use only small case
    - keywords:
      - procedure
      - storedProcedure
      comment: Input params have been cleared after fetching results from procedure


jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: A job to create dynamic checklist
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Dynamic checklist action
        id: dynamic_checklist
        uses: vishalsinha21/dynamic-checklist@v1
        with:
          mappingFile: 'mapping.json'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get the output checklist
        run: echo "The final checklist ${{ steps.dynamic_checklist.outputs.checklist }}"

